### ISSUE TITLE
PoS module questions

### ISSUE THREAD

**Issue by angbrav** [informalsystems/partnership-heliax#3]
### Epochs

- Is there any constraint on the epoch duration (min/max)?

### Bootstrapping a validator

- Is there a minimum amount of self-bounded tokens required for a validator?
- If that's the case, is a validator deactivated when this requirement is violated, e.g, due to slashing?

### Withdraw unbonds

- We do not fully understand what the "withdraw unbonds" action is meant for, both in the context of validators and delegators.

### Voting power computation

- Could we re-visit the paragraph that explains how to compute the voting power of a validator to make it clearer? What is not clear is why the unbonded tokens are subtracted from the sum of self-bonds and delegated bonds.

### Slashing

- We have understood that slashing happens at the end of an epoch. Is that right? 
- The problem we see with that is that a validator that misbehaves at the beginning of an epoch can keep on misbehaving until the end of the epoch.
  - This has some implications: (i) other validators may witness a validator misbehaving for a bunch of blocks without being punished; (ii) a well-intentioned validator that misbehaves due to a bug may unnecessarily misbehave for a range of blocks without knowing it: it may only realize once it gets slashed at the end of the epoch.
  - We see potential benefits from slashing more aggressively. It could be interesting to explore if slashing can be somehow decoupled from the epoch abstraction? We understand this may not be possible as slashing is tightly coupled with other parts of the PoS system such as updating the active validator set.
- The cubic slashing section says that at the end of an epoch, the system iterates over all slashes detected in the past 2 epochs. Even though we discussed it during our chat, we cannot remember the reason why this is done. Could you please clarify it?

### Jail/Unjailing

- What is the relationship between attack types and jailing duration? Are there attacks that make jailing permanent?
- How does unjailing work? We could only find that a validator can submit a transaction to unjail itself after a configurable period of time. Does this mean that there is no automatic unjaling?

### Rewards

- From our chat, we understood that the system only rewards the validators that voted for a given block. In Tendermint, a validator, before moving to a height h+1, waits for a configurable time (timeoutcommit) to gather as many precommit messages for height h as possible (beyond 2f+1). Then, the proposal of block h+1 contains the set of precommit messages for block h known by the proposer. The PoS module then rewards all validators in this set. Does Anoma work similarly?

**Comment by sergio-mena** [comment]
Thanks @FatemeShirazi for all the clarifications during our meeting. To me, the two remaining points on the max transaction limit (see your comment above) are:

* Replace "2/3" by "1/3+1" in the [latests spec](https://github.com/anoma/namada/blob/main/documentation/specs/src/economics/proof-of-stake.md#security) (last paragraph)
* As I said during the meeting, to understand the limit in the last paragraph, one needs to go through some extra info. So, I'd suggest you to consider whether that extra info should be added to the spec for completeness. Alternatively, as you explained, this can rather be considered a requirement for apps such as wallets, rather than to the chain itself, so it might also make sense to remove the reference to the 1/3+ limit from the spec's text.

Thoughts?

**Comment by sergio-mena** [comment]
Thanks @FatemeShirazi for removing the sentence from the spec
