### ISSUE TITLE
Compute total_unbonded more efficietnly

### ISSUE THREAD

**Issue by angbrav** [informalsystems/partnership-heliax#48]
We could solve the iteration over the set_unbonds by grouping unbonds by a pair of bond start epoch and unbond epoch.

**Comment by brentstone** [comment]
This is addressed in Namada in [b7eddc2c46cdc72aafe1abd6c91e8ab9ab929e5c](https://github.com/anoma/namada/pull/892/commits/b7eddc2c46cdc72aafe1abd6c91e8ab9ab929e5c). Will add to #43

**Comment by brentstone** [comment]
Now addressed in the pseudocode in 16bb8860715ad3ebb801c81c18ab019a72f9af7e

**Comment by brentstone** [comment]
Why do we actually use `set_unbonds` as opposed to simply using the `Unbond`s themselves? They both encode the same information I believe: only `set_unbonds` stores the epoch at which an unbond becomes active, while `Unbond` encodes the withdrawal epoch. However, there's a 1 to 1 correspondence between these two epochs.

Perhaps it is because the data structures in the pseudocode are slightly different? However, in Namada, they are implemented the same as `Map<Epoch, Map<Epoch, token::Amount>>`. I wonder if we can just remove this.

**Comment by angbrav** [comment]
I agree all information in `set_unbonds` is in `unbonds`. The idea was to keep them separate to avoid iterating over unbonds. But given the way is implemented in Namada, it is redundant. Nevertheless, with the more efficient way of computing `total_unbonded`, I believe this "problem" goes away.

**Comment by brentstone** [comment]
Completed in #54
